name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the type of runner to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run tests
        run: npm test  # Run your tests

      - name: Fetch README
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Access the secret token
        run: |
          node script.js  # Run your script to fetch the README
